dbConfig:
  - uName: "db_uq_name" #必须唯一 方便索引数据库
    mark: "说明备注"
    host: "localhost"
    port: "3306"
    user: "root"
    pass: "password"
    name: "db_name"
    logLevel: "info" #silent error warn info
    tunnelSSHHost: "1.1.1.1"
    tunnelSSHPort: "22"
    tunnelSSHUser: "sshuser"
    tunnelSSHPassword: "ssh-password"

